services:

  client:
    container_name: client
    restart: always
    build:
      context: video-manager-ui
      target: development
    environment:
      -  SERVER_URL=http://localhost:4000
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./video-manager-ui:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    depends_on:
      - video-manager-api
    expose: 
      - 3000

  storybook:
    container_name: storybook
    restart: always
    command: yarn storybook
    build:
      context: video-manager-ui
      target: development
    ports:
      - 6006:6006
    volumes:
      - ./video-manager-ui:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - video-manager-ui
    expose: 
      - 6006

  server:
    container_name: server
    restart: always
    build:
      context: video-manager-api
      target: development
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/video-manager
    ports:
      - 4000:4000
    volumes:
      - ./video-manager-api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 4000

  mongo:
    container_name: mongo
    restart: always
    image: mongo:5.0.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  react-express:
  express-mongo:
