services:

  video-manager-ui:
    build:
      context: video-manager-ui
      target: dev-envs
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    networks:
      - react-express
    depends_on:
      - video-manager-api

  video-manager-api:
    restart: always
    build:
      context: video-manager-api
      target: dev-envs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express
    expose: 
      - 4000

  mongo:
    restart: always
    image: mongo:5.0.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

networks:
  react-express:
  express-mongo: